In [2]:
#本文是协同过滤模型用于电影推荐
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt
#  Y is a 1682x943 matrix, containing ratings (1-5) of 1682 movies on 
#  943 users
#  R is a 1682x943 matrix, where R(i,j) = 1 if and only if user j gave a
#  rating to movie i
data = sio.loadmat('ex8_movies.mat')

Y = data['Y'] #[1682*943] movies * users
R = data['R'] #[1682*943] 0 or 1
print Y.shape,R.shape
print Y[0:5,0:5]
print 'Average rating for movie 1 (Toy Story): %f / 5'\
      %(np.mean(Y[0,R[0,:]==1]))





(1682L, 943L) (1682L, 943L)
[[5 4 0 0 4]
 [3 0 0 0 3]
 [4 0 0 0 0]
 [3 0 0 0 0]
 [3 0 0 0 0]]
Average rating for movie 1 (Toy Story): 3.878319 / 5


In [3]:
#load movies data set
params = sio.loadmat('ex8_movieParams.mat')
X = params['X']
Theta = params['Theta']
num_users = params['num_users']
num_movies = params['num_movies']
num_features = params['num_features']
print X.shape,Theta.shape
print num_movies,num_users,num_features



(1682L, 10L) (943L, 10L)
[[1682]] [[943]] [[10]]


In [4]:
#compute the cost
#note:no x0 = 1, no 1/m  !!!!!!!!没有x0=1,也没有除以m
def computeCost(x,theta,y,r,reg=0):
    j = 0
    x_grad = np.zeros_like(x)
    theta_grad = np.zeros_like(theta)
    
    j_temp = (x.dot(theta.T) - y)**2
    j = 0.5 * np.sum(j_temp[r==1]) + 0.5 * reg * np.sum(theta**2) \
        + 0.5 * reg * np.sum(x**2) 
    
    x_grad = np.dot(((x.dot(theta.T)-y)*r),theta) + reg * x
    theta_grad = np.dot(((x.dot(theta.T)-y)*r).T,x) + reg * theta
    
    return j,x_grad,theta_grad
    
#Reduce the data set size so that this runs faster
#用一个小模型测试一下算法是否正确
nu, nm, nf = 4, 5, 3
X1 = X[0:nm,0:nf]
Theta1 = Theta[0:nu,0:nf]
Y1 = Y[0:nm,0:nu]
R1 = R[0:nm,0:nu]

#check the cost
J,x_g,theta_g = computeCost(X1,Theta1,Y1,R1,0)
print"reg = 0,this value should be about 22.22\n",J

J2,x_g2,theta_g2 = computeCost(X1,Theta1,Y1,R1,1.5)
print"reg = 1.5,this value should be about 31.34\n",J2

reg = 0,this value should be about 22.22
22.2246037257
reg = 1.5,this value should be about 31.34
31.3440562443


In [5]:
#compute numerical_gradient数值计算梯度
def eval_numerical_gradient(f, x, verbose=True, h=0.00001):
    """ 
    a naive implementation of numerical gradient of f at x 
    - f should be a function that takes a single argument
    - x is the point (numpy array) to evaluate the gradient at
    """ 
    
    fx = f(x) # evaluate function value at original point
    grad = np.zeros_like(x)
    # iterate over all indexes in x
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        
        # evaluate function at x+h
        ix = it.multi_index
        oldval = x[ix]
        x[ix] = oldval + h # increment by h
        fxph = f(x) # evalute f(x + h)
        x[ix] = oldval - h
        fxmh = f(x) # evaluate f(x - h)
        x[ix] = oldval # restore
        
        # compute the partial derivative with centered formula
        grad[ix] = (fxph - fxmh) / (2 * h) # the slope
        if verbose:
          print ix, grad[ix]
        it.iternext() # step to next dimension
    return grad

def rel_error(x, y):
  """ returns relative error """
  return np.max(np.abs(x - y) / (np.maximum(1e-8, np.abs(x) + np.abs(y))))


In [6]:
#check the gradient ,进行梯度检查，一般都是产生小数字，小模型，因为数值梯度计算量太大
#create the small data

x_t = np.random.rand(4,3)
theta_t = np.random.rand(5,3)
y_t = x_t.dot(theta_t.T) #4,5
y_t[np.random.rand(*y_t.shape)>0.5] = 0
r_t = np.zeros_like(y_t)
r_t[y_t != 0] = 1
#print y_t,r_t

X_t = np.random.randn(*x_t.shape)
Theta_t = np.random.randn(*theta_t.shape)
nu_t = 5
nm_t = 4
nf_t = 3


j,x_grad,theta_grad = computeCost(X_t,Theta_t,y_t,r_t,1.5)
f = lambda W:computeCost(X_t,Theta_t,y_t,r_t,1.5)[0] #f = J(x)
x_grad1 = eval_numerical_gradient(f,X_t , verbose=False, h=0.00001)
theta_grad1 = eval_numerical_gradient(f, Theta_t, verbose=False, h=0.00001)
#放在一起对比一下，前三列是x_grad，后三列是x_grad1
display_X = np.hstack((x_grad,x_grad1))
print display_X
display_Theta = np.hstack((theta_grad,theta_grad1))
print display_Theta

print '%s max relative error: %e' % ('x', rel_error(x_grad, x_grad1))
print '%s max relative error: %e' % \
      ('theta', rel_error(theta_grad, theta_grad1))



[[ -1.4485962   -2.38226893   1.70710777  -1.4485962   -2.38226893
    1.70710777]
 [ -2.18041855   6.88240991  -7.8848515   -2.18041855   6.88240991
   -7.8848515 ]
 [  8.23023857  -1.02191424  -4.0025453    8.23023857  -1.02191424
   -4.0025453 ]
 [ 14.13447555  -5.85369614  -5.0379881   14.13447555  -5.85369614
   -5.0379881 ]]
[[  0.73826162   2.09184519  -0.48151182   0.73826162   2.09184519
   -0.48151182]
 [  1.18589767   1.21853183  -1.81195221   1.18589767   1.21853183
   -1.81195221]
 [ -5.30305981   8.71447069 -11.02419571  -5.30305981   8.71447069
  -11.02419571]
 [ 10.43018863  -4.31754416  -6.23177659  10.43018863  -4.31754416
   -6.23177659]
 [  0.27896481  -1.40228679   1.58240075   0.27896481  -1.40228679
    1.58240075]]
x max relative error: 6.712613e-11
theta max relative error: 1.661263e-10


In [7]:
def load_data(filename):#导入电影数据
    movieList = []
    file = open(filename)
    for line in file.readlines():
        lineArr = line.strip().split(' ')
        col_num = len(lineArr)
        temp = ''
        for i in xrange(col_num):
            if i==0:
                continue
            temp= temp + lineArr[i] + ' '
        movieList.append(temp)
    return movieList

movieList = load_data('movie_ids.txt')
print movieList[:5]


['Toy Story (1995) ', 'GoldenEye (1995) ', 'Four Rooms (1995) ', 'Get Shorty (1995) ', 'Copycat (1995) ']


In [8]:
#Entering ratings for a new user
my_ratings = np.zeros((1682,1))
my_ratings[0] = 4
my_ratings[97] = 2
my_ratings[6] = 3
my_ratings[11]= 5
my_ratings[53] = 4
my_ratings[63]= 5
my_ratings[65]= 3
my_ratings[68] = 5
my_ratings[182] = 4
my_ratings[225] = 5
my_ratings[354]= 5
for i in range(1682):
    if my_ratings[i]>0:
        print "Rated %d for %s" %(my_ratings[i],movieList[i])






Rated 4 for Toy Story (1995) 
Rated 3 for Twelve Monkeys (1995) 
Rated 5 for Usual Suspects, The (1995) 
Rated 4 for Outbreak (1995) 
Rated 5 for Shawshank Redemption, The (1994) 
Rated 3 for While You Were Sleeping (1995) 
Rated 5 for Forrest Gump (1994) 
Rated 2 for Silence of the Lambs, The (1991) 
Rated 4 for Alien (1979) 
Rated 5 for Die Hard 2 (1990) 
Rated 5 for Sphere (1998) 


In [9]:
#Learning Movie Ratings
#将新的用户的评分数据放入数据集合,进行训练
#Add our own ratings to the data matrix
YY = np.hstack((my_ratings,Y))
RR = np.hstack((my_ratings!=0,R))
print YY.shape,RR.shape
#Normalize Ratings
#进行数值归一化
def normalizeRatings(y,r):
    m,n = y.shape
    ymean = np.zeros((m,1))
    ynorm = np.zeros_like(y)
    for i in xrange(m):
        idx = np.where(r[i,:]==1)
        ymean[i] = np.mean(y[i,idx])
        ynorm[i,idx] = y[i,idx] - ymean[i]
        
    return ymean,ynorm
    
Ymean,Ynorm = normalizeRatings(YY,RR)

num_users1 = YY.shape[1]
num_movies1 = YY.shape[0]
num_features1 = 10
#Set Initial Parameters (Theta, X)
XX = np.random.randn(num_movies1,num_features1)
TTheta = np.random.randn(num_users1,num_features1)
print XX.shape
print TTheta.shape

(1682L, 944L) (1682L, 944L)
(1682L, 10L)
(944L, 10L)


In [10]:
from scipy import optimize
#还是使用优化算法去训练

args = (Ynorm,RR,num_users1,num_movies1,num_features1,1.5)
params = np.hstack((XX.ravel(),TTheta.ravel())).ravel()
#we use the scipy.optimize.fmin_cg,so we need to change the 
#function computeCost(),beacause x must be 1-D
def Cost(params,*args):
    '''now params is 1-D,include [x,theta]'''
    y,r,nu,nm,nf,reg = args
    j = 0
    x = params[0:nm*nf].reshape(nm,nf)
    theta = params[nm*nf:].reshape(nu,nf)
    
    j_temp = (x.dot(theta.T) - y)**2
    j = 0.5 * np.sum(j_temp[r==1]) + 0.5 * reg * np.sum(theta**2) \
        + 0.5 * reg * np.sum(x**2) 
    
    return j

def grad(params,*args):
    y,r,nu,nm,nf,reg = args
    #unfold into x and theta
    x = params[0:nm*nf].reshape(nm,nf)
    theta = params[nm*nf:].reshape(nu,nf)
    x_grad = np.zeros_like(x)
    theta_grad = np.zeros_like(theta)
    x_grad = np.dot(((x.dot(theta.T)-y)*r),theta) + reg * x
    theta_grad = np.dot(((x.dot(theta.T)-y)*r).T,x) + reg * theta
    #fold the x_grad and theta_grad
    g = np.hstack((x_grad.ravel(),theta_grad.ravel())).ravel()
    return g

    
res = optimize.fmin_cg(Cost,x0=params,fprime=grad,args=args,maxiter=100)


         Current function value: 27696.300753
         Iterations: 100
         Function evaluations: 149
         Gradient evaluations: 149


In [11]:
#get the bestX,bestTheta
#改变一下参数的shape
bestX = res[0:num_movies1*num_features1].reshape(num_movies1,num_features1)
bestTheta = res[num_movies1*num_features1:].reshape(num_users1,num_features1)


print bestX.shape,bestTheta.shape
#预测一下分数
score = bestX.dot(bestTheta.T) + Ymean
#只有第一行是新用户的分数
my_score = score[:,0]  #line 1 is my scoce
print score.shape
print my_score[:5]
#排序，推荐最高的分数的电影给新用户
sort_index = my_score.argsort()
favorite = 10
for i in xrange(favorite):
    print "favorite %d score is %d,for:%s" \
          %(i+1,my_score[sort_index[-(i+1)]],movieList[sort_index[-(i+1)]])
    



(1682L, 10L) (944L, 10L)
(1682L, 944L)
[ 3.83399475  3.34586129  4.46180229  3.76026786  3.44922026]
favorite 1 score is 5,for:Return of the Jedi (1983) 
favorite 2 score is 5,for:Star Wars (1977) 
favorite 3 score is 5,for:Empire Strikes Back, The (1980) 
favorite 4 score is 5,for:Independence Day (ID4) (1996) 
favorite 5 score is 5,for:Renaissance Man (1994) 
favorite 6 score is 5,for:Star Kid (1997) 
favorite 7 score is 5,for:Marlene Dietrich: Shadow and Light (1996) 
favorite 8 score is 5,for:Saint of Fort Washington, The (1993) 
favorite 9 score is 5,for:Santa with Muscles (1996) 
favorite 10 score is 5,for:Someone Else's America (1995) 
